/* soapStub.h
   Generated by gSOAP 2.7.16 from sugar_soap.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapStub_H
#define soapStub_H
#define SOAP_NAMESPACE_OF_ns1	"http://www.sugarcrm.com/sugarcrm"
#include "sugar_stdsoap2.h"
#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (7)
/* xsd:boolean */
enum xsd__boolean {xsd__boolean__false_ = 0, xsd__boolean__true_ = 1};
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not redeclare here */

#endif

#ifndef SOAP_TYPE_ns1__new_USCOREnote_USCOREattachment
#define SOAP_TYPE_ns1__new_USCOREnote_USCOREattachment (8)
/* ns1:new_note_attachment */
struct ns1__new_USCOREnote_USCOREattachment
{
	char *id;	/* required element of type xsd:string */
	char *filename;	/* required element of type xsd:string */
	char *file;	/* required element of type xsd:string */
	char *related_USCOREmodule_USCOREid;	/* required element of type xsd:string */
	char *related_USCOREmodule_USCOREname;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__new_USCOREreturn_USCOREnote_USCOREattachment
#define SOAP_TYPE_ns1__new_USCOREreturn_USCOREnote_USCOREattachment (9)
/* ns1:new_return_note_attachment */
struct ns1__new_USCOREreturn_USCOREnote_USCOREattachment
{
	struct ns1__new_USCOREnote_USCOREattachment *note_USCOREattachment;	/* required element of type ns1:new_note_attachment */
};
#endif

#ifndef SOAP_TYPE_ns1__user_USCOREauth
#define SOAP_TYPE_ns1__user_USCOREauth (11)
/* ns1:user_auth */
struct ns1__user_USCOREauth
{
	char *user_USCOREname;	/* required element of type xsd:string */
	char *password;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__field
#define SOAP_TYPE_ns1__field (12)
/* ns1:field */
struct ns1__field
{
	char *name;	/* required element of type xsd:string */
	char *type;	/* required element of type xsd:string */
	char *group;	/* required element of type xsd:string */
	char *label;	/* required element of type xsd:string */
	int required;	/* required element of type xsd:int */
	struct name_USCOREvalue_USCORElist *options;	/* required element of type ArrayOfname-value */
	char *default_USCOREvalue;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__link_USCOREfield
#define SOAP_TYPE_ns1__link_USCOREfield (15)
/* ns1:link_field */
struct ns1__link_USCOREfield
{
	char *name;	/* required element of type xsd:string */
	char *type;	/* required element of type xsd:string */
	char *relationship;	/* required element of type xsd:string */
	char *module;	/* required element of type xsd:string */
	char *bean_USCOREname;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__name_USCOREvalue
#define SOAP_TYPE_ns1__name_USCOREvalue (16)
/* ns1:name_value */
struct ns1__name_USCOREvalue
{
	char *name;	/* required element of type xsd:string */
	char *value;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__new_USCOREmodule_USCOREfields
#define SOAP_TYPE_ns1__new_USCOREmodule_USCOREfields (17)
/* ns1:new_module_fields */
struct ns1__new_USCOREmodule_USCOREfields
{
	char *module_USCOREname;	/* required element of type xsd:string */
	char *table_USCOREname;	/* required element of type xsd:string */
	struct field_USCORElist *module_USCOREfields;	/* required element of type ArrayOffield */
	struct link_USCOREfield_USCORElist *link_USCOREfields;	/* required element of type ArrayOflink-field */
};
#endif

#ifndef SOAP_TYPE_ns1__entry_USCOREvalue
#define SOAP_TYPE_ns1__entry_USCOREvalue (22)
/* ns1:entry_value */
struct ns1__entry_USCOREvalue
{
	char *id;	/* required element of type xsd:string */
	char *module_USCOREname;	/* required element of type xsd:string */
	struct name_USCOREvalue_USCORElist *name_USCOREvalue_USCORElist;	/* required element of type ArrayOfname-value */
};
#endif

#ifndef SOAP_TYPE_ns1__set_USCOREentries_USCOREdetail_USCOREresult
#define SOAP_TYPE_ns1__set_USCOREentries_USCOREdetail_USCOREresult (23)
/* ns1:set_entries_detail_result */
struct ns1__set_USCOREentries_USCOREdetail_USCOREresult
{
	struct name_USCOREvalue_USCORElists *name_USCOREvalue_USCORElists;	/* required element of type ArrayOfArrayOfname-value */
};
#endif

#ifndef SOAP_TYPE_ns1__link_USCOREname_USCOREto_USCOREfields_USCOREarray
#define SOAP_TYPE_ns1__link_USCOREname_USCOREto_USCOREfields_USCOREarray (26)
/* ns1:link_name_to_fields_array */
struct ns1__link_USCOREname_USCOREto_USCOREfields_USCOREarray
{
	char *name;	/* required element of type xsd:string */
	struct select_USCOREfields *value;	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__link_USCOREname_USCOREvalue
#define SOAP_TYPE_ns1__link_USCOREname_USCOREvalue (29)
/* ns1:link_name_value */
struct ns1__link_USCOREname_USCOREvalue
{
	char *name;	/* required element of type xsd:string */
	struct link_USCOREarray_USCORElist *records;	/* required element of type ArrayOflink-value2 */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREentry_USCOREresult_USCOREversion2
#define SOAP_TYPE_ns1__get_USCOREentry_USCOREresult_USCOREversion2 (32)
/* ns1:get_entry_result_version2 */
struct ns1__get_USCOREentry_USCOREresult_USCOREversion2
{
	struct entry_USCORElist *entry_USCORElist;	/* required element of type ArrayOfentry-value */
	struct link_USCORElists *relationship_USCORElist;	/* required element of type ArrayOflink-list2 */
};
#endif

#ifndef SOAP_TYPE_ns1__return_USCOREsearch_USCOREresult
#define SOAP_TYPE_ns1__return_USCOREsearch_USCOREresult (37)
/* ns1:return_search_result */
struct ns1__return_USCOREsearch_USCOREresult
{
	struct search_USCORElink_USCORElist *entry_USCORElist;	/* required element of type ArrayOfsearch-link-name-value */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREentry_USCORElist_USCOREresult_USCOREversion2
#define SOAP_TYPE_ns1__get_USCOREentry_USCORElist_USCOREresult_USCOREversion2 (40)
/* ns1:get_entry_list_result_version2 */
struct ns1__get_USCOREentry_USCORElist_USCOREresult_USCOREversion2
{
	int result_USCOREcount;	/* required element of type xsd:int */
	int total_USCOREcount;	/* required element of type xsd:int */
	int next_USCOREoffset;	/* required element of type xsd:int */
	struct entry_USCORElist *entry_USCORElist;	/* required element of type ArrayOfentry-value */
	struct link_USCORElists *relationship_USCORElist;	/* required element of type ArrayOflink-list2 */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREserver_USCOREinfo_USCOREresult
#define SOAP_TYPE_ns1__get_USCOREserver_USCOREinfo_USCOREresult (41)
/* ns1:get_server_info_result */
struct ns1__get_USCOREserver_USCOREinfo_USCOREresult
{
	char *flavor;	/* required element of type xsd:string */
	char *version;	/* required element of type xsd:string */
	char *gmt_USCOREtime;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__new_USCOREset_USCOREentry_USCOREresult
#define SOAP_TYPE_ns1__new_USCOREset_USCOREentry_USCOREresult (42)
/* ns1:new_set_entry_result */
struct ns1__new_USCOREset_USCOREentry_USCOREresult
{
	char *id;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__new_USCOREset_USCOREentries_USCOREresult
#define SOAP_TYPE_ns1__new_USCOREset_USCOREentries_USCOREresult (43)
/* ns1:new_set_entries_result */
struct ns1__new_USCOREset_USCOREentries_USCOREresult
{
	struct select_USCOREfields *ids;	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__new_USCOREset_USCORErelationship_USCORElist_USCOREresult
#define SOAP_TYPE_ns1__new_USCOREset_USCORErelationship_USCORElist_USCOREresult (44)
/* ns1:new_set_relationship_list_result */
struct ns1__new_USCOREset_USCORErelationship_USCORElist_USCOREresult
{
	int created;	/* required element of type xsd:int */
	int failed;	/* required element of type xsd:int */
	int deleted;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__document_USCORErevision
#define SOAP_TYPE_ns1__document_USCORErevision (45)
/* ns1:document_revision */
struct ns1__document_USCORErevision
{
	char *id;	/* required element of type xsd:string */
	char *document_USCOREname;	/* required element of type xsd:string */
	char *revision;	/* required element of type xsd:string */
	char *filename;	/* required element of type xsd:string */
	char *file;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__new_USCOREreturn_USCOREdocument_USCORErevision
#define SOAP_TYPE_ns1__new_USCOREreturn_USCOREdocument_USCORErevision (46)
/* ns1:new_return_document_revision */
struct ns1__new_USCOREreturn_USCOREdocument_USCORErevision
{
	struct ns1__document_USCORErevision *document_USCORErevision;	/* required element of type ns1:document_revision */
};
#endif

#ifndef SOAP_TYPE_ns1__module_USCORElist
#define SOAP_TYPE_ns1__module_USCORElist (48)
/* ns1:module_list */
struct ns1__module_USCORElist
{
	struct module_USCORElist_USCOREarray *modules;	/* required element of type ArrayOfmodule-list-entry */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREentries_USCOREcount_USCOREresult
#define SOAP_TYPE_ns1__get_USCOREentries_USCOREcount_USCOREresult (51)
/* ns1:get_entries_count_result */
struct ns1__get_USCOREentries_USCOREcount_USCOREresult
{
	int result_USCOREcount;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__upcoming_USCOREactivity_USCOREentry
#define SOAP_TYPE_ns1__upcoming_USCOREactivity_USCOREentry (52)
/* ns1:upcoming_activity_entry */
struct ns1__upcoming_USCOREactivity_USCOREentry
{
	char *id;	/* required element of type xsd:string */
	char *module;	/* required element of type xsd:string */
	char *date_USCOREdue;	/* required element of type xsd:string */
	char *summary;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__last_USCOREviewed_USCOREentry
#define SOAP_TYPE_ns1__last_USCOREviewed_USCOREentry (53)
/* ns1:last_viewed_entry */
struct ns1__last_USCOREviewed_USCOREentry
{
	char *id;	/* required element of type xsd:string */
	char *item_USCOREid;	/* required element of type xsd:string */
	char *item_USCOREsummary;	/* required element of type xsd:string */
	char *module_USCOREname;	/* required element of type xsd:string */
	char *monitor_USCOREid;	/* required element of type xsd:string */
	char *date_USCOREmodified;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__module_USCORElist_USCOREentry
#define SOAP_TYPE_ns1__module_USCORElist_USCOREentry (54)
/* ns1:module_list_entry */
struct ns1__module_USCORElist_USCOREentry
{
	char *module_USCOREkey;	/* required element of type xsd:string */
	char *module_USCORElabel;	/* required element of type xsd:string */
	enum xsd__boolean favorite_USCOREenabled;	/* required element of type xsd:boolean */
	struct acl_USCORElist *acls;	/* required element of type ArrayOfacl-list-entry */
};
#endif

#ifndef SOAP_TYPE_ns1__acl_USCORElist_USCOREentry
#define SOAP_TYPE_ns1__acl_USCORElist_USCOREentry (57)
/* ns1:acl_list_entry */
struct ns1__acl_USCORElist_USCOREentry
{
	char *action;	/* required element of type xsd:string */
	char *access;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__link_USCORElist2
#define SOAP_TYPE_ns1__link_USCORElist2 (58)
/* ns1:link_list2 */
struct ns1__link_USCORElist2
{
	struct link_USCORElist *link_USCORElist;	/* required element of type ArrayOflink-name-value */
};
#endif

#ifndef SOAP_TYPE_ns1__link_USCOREvalue2
#define SOAP_TYPE_ns1__link_USCOREvalue2 (61)
/* ns1:link_value2 */
struct ns1__link_USCOREvalue2
{
	struct link_USCOREvalue *link_USCOREvalue;	/* required element of type ArrayOfname-value */
};
#endif

#ifndef SOAP_TYPE_ns1__field_USCORElist2
#define SOAP_TYPE_ns1__field_USCORElist2 (64)
/* ns1:field_list2 */
struct ns1__field_USCORElist2
{
	struct field_USCORElist *field_USCORElist;	/* required element of type ArrayOffield */
};
#endif

#ifndef SOAP_TYPE_ns1__entry_USCORElist2
#define SOAP_TYPE_ns1__entry_USCORElist2 (65)
/* ns1:entry_list2 */
struct ns1__entry_USCORElist2
{
	struct entry_USCORElist *entry_USCORElist;	/* required element of type ArrayOfentry-value */
};
#endif

#ifndef SOAP_TYPE_ns1__search_USCORElink_USCOREname_USCOREvalue
#define SOAP_TYPE_ns1__search_USCORElink_USCOREname_USCOREvalue (66)
/* ns1:search_link_name_value */
struct ns1__search_USCORElink_USCOREname_USCOREvalue
{
	char *name;	/* required element of type xsd:string */
	struct search_USCORElink_USCOREarray_USCORElist *records;	/* required element of type ArrayOfArrayOfname-value */
};
#endif

#ifndef SOAP_TYPE_ns1__error_USCOREvalue
#define SOAP_TYPE_ns1__error_USCOREvalue (69)
/* ns1:error_value */
struct ns1__error_USCOREvalue
{
	char *number;	/* required element of type xsd:string */
	char *name;	/* required element of type xsd:string */
	char *description;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__modified_USCORErelationship_USCOREentry
#define SOAP_TYPE_ns1__modified_USCORErelationship_USCOREentry (70)
/* ns1:modified_relationship_entry */
struct ns1__modified_USCORErelationship_USCOREentry
{
	char *id;	/* required element of type xsd:string */
	char *module_USCOREname;	/* required element of type xsd:string */
	struct name_USCOREvalue_USCORElist *name_USCOREvalue_USCORElist;	/* required element of type ArrayOfname-value */
};
#endif

#ifndef SOAP_TYPE_ns1__modified_USCORErelationship_USCOREresult
#define SOAP_TYPE_ns1__modified_USCORErelationship_USCOREresult (71)
/* ns1:modified_relationship_result */
struct ns1__modified_USCORErelationship_USCOREresult
{
	int result_USCOREcount;	/* required element of type xsd:int */
	int next_USCOREoffset;	/* required element of type xsd:int */
	struct modified_USCORErelationship_USCOREentry_USCORElist *entry_USCORElist;	/* required element of type ArrayOfmodified-relationship-entry */
	struct ns1__error_USCOREvalue *error;	/* required element of type ns1:error_value */
};
#endif

#ifndef SOAP_TYPE_field_USCORElist
#define SOAP_TYPE_field_USCORElist (18)
/* SOAP encoded array of ns1:field schema type: */
struct field_USCORElist
{
	struct ns1__field **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_link_USCOREfield_USCORElist
#define SOAP_TYPE_link_USCOREfield_USCORElist (20)
/* SOAP encoded array of ns1:link_field schema type: */
struct link_USCOREfield_USCORElist
{
	struct ns1__link_USCOREfield **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_name_USCOREvalue_USCORElist
#define SOAP_TYPE_name_USCOREvalue_USCORElist (13)
/* SOAP encoded array of ns1:name_value schema type: */
struct name_USCOREvalue_USCORElist
{
	struct ns1__name_USCOREvalue **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_name_USCOREvalue_USCORElists
#define SOAP_TYPE_name_USCOREvalue_USCORElists (24)
/* SOAP encoded array of ns1:name_value schema type: */
struct name_USCOREvalue_USCORElists
{
	struct name_USCOREvalue_USCORElist **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_select_USCOREfields
#define SOAP_TYPE_select_USCOREfields (27)
/* SOAP encoded array of xsd:string schema type: */
struct select_USCOREfields
{
	char **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_deleted_USCOREarray
#define SOAP_TYPE_deleted_USCOREarray (83)
/* SOAP encoded array of xsd:int schema type: */
struct deleted_USCOREarray
{
	int *__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_entry_USCORElist
#define SOAP_TYPE_entry_USCORElist (33)
/* SOAP encoded array of ns1:entry_value schema type: */
struct entry_USCORElist
{
	struct ns1__entry_USCOREvalue **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_link_USCOREnames_USCOREto_USCOREfields_USCOREarray
#define SOAP_TYPE_link_USCOREnames_USCOREto_USCOREfields_USCOREarray (87)
/* SOAP encoded array of ns1:link_name_to_fields_array schema type: */
struct link_USCOREnames_USCOREto_USCOREfields_USCOREarray
{
	struct ns1__link_USCOREname_USCOREto_USCOREfields_USCOREarray **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_link_USCOREvalue
#define SOAP_TYPE_link_USCOREvalue (62)
/* SOAP encoded array of ns1:name_value schema type: */
struct link_USCOREvalue
{
	struct ns1__name_USCOREvalue **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_link_USCOREarray_USCORElist
#define SOAP_TYPE_link_USCOREarray_USCORElist (30)
/* SOAP encoded array of ns1:link_value2 schema type: */
struct link_USCOREarray_USCORElist
{
	struct ns1__link_USCOREvalue2 **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_link_USCORElist
#define SOAP_TYPE_link_USCORElist (59)
/* SOAP encoded array of ns1:link_name_value schema type: */
struct link_USCORElist
{
	struct ns1__link_USCOREname_USCOREvalue **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_link_USCORElists
#define SOAP_TYPE_link_USCORElists (35)
/* SOAP encoded array of ns1:link_list2 schema type: */
struct link_USCORElists
{
	struct ns1__link_USCORElist2 **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_new_USCOREset_USCORErelationhip_USCOREids
#define SOAP_TYPE_new_USCOREset_USCORErelationhip_USCOREids (96)
/* SOAP encoded array of xsd:string schema type: */
struct new_USCOREset_USCORErelationhip_USCOREids
{
	struct select_USCOREfields **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_md5_USCOREresults
#define SOAP_TYPE_md5_USCOREresults (98)
/* SOAP encoded array of xsd:string schema type: */
struct md5_USCOREresults
{
	char **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_module_USCOREnames
#define SOAP_TYPE_module_USCOREnames (99)
/* SOAP encoded array of xsd:string schema type: */
struct module_USCOREnames
{
	char **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_upcoming_USCOREactivities_USCORElist
#define SOAP_TYPE_upcoming_USCOREactivities_USCORElist (100)
/* SOAP encoded array of ns1:upcoming_activity_entry schema type: */
struct upcoming_USCOREactivities_USCORElist
{
	struct ns1__upcoming_USCOREactivity_USCOREentry **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_last_USCOREviewed_USCORElist
#define SOAP_TYPE_last_USCOREviewed_USCORElist (103)
/* SOAP encoded array of ns1:last_viewed_entry schema type: */
struct last_USCOREviewed_USCORElist
{
	struct ns1__last_USCOREviewed_USCOREentry **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_module_USCORElist_USCOREarray
#define SOAP_TYPE_module_USCORElist_USCOREarray (49)
/* SOAP encoded array of ns1:module_list_entry schema type: */
struct module_USCORElist_USCOREarray
{
	struct ns1__module_USCORElist_USCOREentry **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_acl_USCORElist
#define SOAP_TYPE_acl_USCORElist (55)
/* SOAP encoded array of ns1:acl_list_entry schema type: */
struct acl_USCORElist
{
	struct ns1__acl_USCORElist_USCOREentry **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_report_USCOREfield_USCORElist
#define SOAP_TYPE_report_USCOREfield_USCORElist (110)
/* SOAP encoded array of ns1:field_list2 schema type: */
struct report_USCOREfield_USCORElist
{
	struct ns1__field_USCORElist2 **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_report_USCOREentry_USCORElist
#define SOAP_TYPE_report_USCOREentry_USCORElist (113)
/* SOAP encoded array of ns1:entry_list2 schema type: */
struct report_USCOREentry_USCORElist
{
	struct ns1__entry_USCORElist2 **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_search_USCORElink_USCORElist
#define SOAP_TYPE_search_USCORElink_USCORElist (38)
/* SOAP encoded array of ns1:search_link_name_value schema type: */
struct search_USCORElink_USCORElist
{
	struct ns1__search_USCORElink_USCOREname_USCOREvalue **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_search_USCORElink_USCOREarray_USCORElist
#define SOAP_TYPE_search_USCORElink_USCOREarray_USCORElist (67)
/* SOAP encoded array of ns1:name_value schema type: */
struct search_USCORElink_USCOREarray_USCORElist
{
	struct link_USCOREvalue **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_modified_USCORErelationship_USCOREentry_USCORElist
#define SOAP_TYPE_modified_USCORErelationship_USCOREentry_USCORElist (72)
/* SOAP encoded array of ns1:modified_relationship_entry schema type: */
struct modified_USCORErelationship_USCOREentry_USCORElist
{
	struct ns1__modified_USCORErelationship_USCOREentry **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ns1__loginResponse
#define SOAP_TYPE_ns1__loginResponse (121)
/* ns1:loginResponse */
struct ns1__loginResponse
{
	struct ns1__entry_USCOREvalue *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:entry_value */
};
#endif

#ifndef SOAP_TYPE_ns1__login
#define SOAP_TYPE_ns1__login (125)
/* ns1:login */
struct ns1__login
{
	struct ns1__user_USCOREauth *user_USCOREauth;	/* optional element of type ns1:user_auth */
	char *application_USCOREname;	/* optional element of type xsd:string */
	struct name_USCOREvalue_USCORElist *name_USCOREvalue_USCORElist;	/* optional element of type ArrayOfname-value */
};
#endif

#ifndef SOAP_TYPE_ns1__logoutResponse
#define SOAP_TYPE_ns1__logoutResponse (126)
/* ns1:logoutResponse */
struct ns1__logoutResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_ns1__logout
#define SOAP_TYPE_ns1__logout (129)
/* ns1:logout */
struct ns1__logout
{
	char *session;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREentryResponse
#define SOAP_TYPE_ns1__get_USCOREentryResponse (130)
/* ns1:get_entryResponse */
struct ns1__get_USCOREentryResponse
{
	struct ns1__get_USCOREentry_USCOREresult_USCOREversion2 *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:get_entry_result_version2 */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREentry
#define SOAP_TYPE_ns1__get_USCOREentry (135)
/* ns1:get_entry */
struct ns1__get_USCOREentry
{
	char *session;	/* optional element of type xsd:string */
	char *module_USCOREname;	/* optional element of type xsd:string */
	char *id;	/* optional element of type xsd:string */
	struct select_USCOREfields *select_USCOREfields;	/* optional element of type ArrayOfstring */
	struct link_USCOREnames_USCOREto_USCOREfields_USCOREarray *link_USCOREname_USCOREto_USCOREfields_USCOREarray;	/* optional element of type ArrayOflink-name-to-fields-array */
	enum xsd__boolean track_USCOREview;	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREentriesResponse
#define SOAP_TYPE_ns1__get_USCOREentriesResponse (136)
/* ns1:get_entriesResponse */
struct ns1__get_USCOREentriesResponse
{
	struct ns1__get_USCOREentry_USCOREresult_USCOREversion2 *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:get_entry_result_version2 */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREentries
#define SOAP_TYPE_ns1__get_USCOREentries (139)
/* ns1:get_entries */
struct ns1__get_USCOREentries
{
	char *session;	/* optional element of type xsd:string */
	char *module_USCOREname;	/* optional element of type xsd:string */
	struct select_USCOREfields *ids;	/* optional element of type ArrayOfstring */
	struct select_USCOREfields *select_USCOREfields;	/* optional element of type ArrayOfstring */
	struct link_USCOREnames_USCOREto_USCOREfields_USCOREarray *link_USCOREname_USCOREto_USCOREfields_USCOREarray;	/* optional element of type ArrayOflink-name-to-fields-array */
	enum xsd__boolean track_USCOREview;	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREentry_USCORElistResponse
#define SOAP_TYPE_ns1__get_USCOREentry_USCORElistResponse (140)
/* ns1:get_entry_listResponse */
struct ns1__get_USCOREentry_USCORElistResponse
{
	struct ns1__get_USCOREentry_USCORElist_USCOREresult_USCOREversion2 *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:get_entry_list_result_version2 */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREentry_USCORElist
#define SOAP_TYPE_ns1__get_USCOREentry_USCORElist (144)
/* ns1:get_entry_list */
struct ns1__get_USCOREentry_USCORElist
{
	char *session;	/* optional element of type xsd:string */
	char *module_USCOREname;	/* optional element of type xsd:string */
	char *query;	/* optional element of type xsd:string */
	char *order_USCOREby;	/* optional element of type xsd:string */
	int offset;	/* required element of type xsd:int */
	struct select_USCOREfields *select_USCOREfields;	/* optional element of type ArrayOfstring */
	struct link_USCOREnames_USCOREto_USCOREfields_USCOREarray *link_USCOREname_USCOREto_USCOREfields_USCOREarray;	/* optional element of type ArrayOflink-name-to-fields-array */
	int max_USCOREresults;	/* required element of type xsd:int */
	int deleted;	/* required element of type xsd:int */
	enum xsd__boolean favorites;	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_ns1__set_USCORErelationshipResponse
#define SOAP_TYPE_ns1__set_USCORErelationshipResponse (145)
/* ns1:set_relationshipResponse */
struct ns1__set_USCORErelationshipResponse
{
	struct ns1__new_USCOREset_USCORErelationship_USCORElist_USCOREresult *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:new_set_relationship_list_result */
};
#endif

#ifndef SOAP_TYPE_ns1__set_USCORErelationship
#define SOAP_TYPE_ns1__set_USCORErelationship (149)
/* ns1:set_relationship */
struct ns1__set_USCORErelationship
{
	char *session;	/* optional element of type xsd:string */
	char *module_USCOREname;	/* optional element of type xsd:string */
	char *module_USCOREid;	/* optional element of type xsd:string */
	char *link_USCOREfield_USCOREname;	/* optional element of type xsd:string */
	struct select_USCOREfields *related_USCOREids;	/* optional element of type ArrayOfstring */
	struct name_USCOREvalue_USCORElist *name_USCOREvalue_USCORElist;	/* optional element of type ArrayOfname-value */
	int delete_;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__set_USCORErelationshipsResponse
#define SOAP_TYPE_ns1__set_USCORErelationshipsResponse (150)
/* ns1:set_relationshipsResponse */
struct ns1__set_USCORErelationshipsResponse
{
	struct ns1__new_USCOREset_USCORErelationship_USCORElist_USCOREresult *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:new_set_relationship_list_result */
};
#endif

#ifndef SOAP_TYPE_ns1__set_USCORErelationships
#define SOAP_TYPE_ns1__set_USCORErelationships (155)
/* ns1:set_relationships */
struct ns1__set_USCORErelationships
{
	char *session;	/* optional element of type xsd:string */
	struct select_USCOREfields *module_USCOREnames;	/* optional element of type ArrayOfstring */
	struct select_USCOREfields *module_USCOREids;	/* optional element of type ArrayOfstring */
	struct select_USCOREfields *link_USCOREfield_USCOREnames;	/* optional element of type ArrayOfstring */
	struct new_USCOREset_USCORErelationhip_USCOREids *related_USCOREids;	/* optional element of type ArrayOfArrayOfstring */
	struct name_USCOREvalue_USCORElists *name_USCOREvalue_USCORElists;	/* optional element of type ArrayOfArrayOfname-value */
	struct deleted_USCOREarray *delete_USCOREarray;	/* optional element of type ArrayOfint */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCORErelationshipsResponse
#define SOAP_TYPE_ns1__get_USCORErelationshipsResponse (156)
/* ns1:get_relationshipsResponse */
struct ns1__get_USCORErelationshipsResponse
{
	struct ns1__get_USCOREentry_USCOREresult_USCOREversion2 *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:get_entry_result_version2 */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCORErelationships
#define SOAP_TYPE_ns1__get_USCORErelationships (159)
/* ns1:get_relationships */
struct ns1__get_USCORErelationships
{
	char *session;	/* optional element of type xsd:string */
	char *module_USCOREname;	/* optional element of type xsd:string */
	char *module_USCOREid;	/* optional element of type xsd:string */
	char *link_USCOREfield_USCOREname;	/* optional element of type xsd:string */
	char *related_USCOREmodule_USCOREquery;	/* optional element of type xsd:string */
	struct select_USCOREfields *related_USCOREfields;	/* optional element of type ArrayOfstring */
	struct link_USCOREnames_USCOREto_USCOREfields_USCOREarray *related_USCOREmodule_USCORElink_USCOREname_USCOREto_USCOREfields_USCOREarray;	/* optional element of type ArrayOflink-name-to-fields-array */
	int deleted;	/* required element of type xsd:int */
	char *order_USCOREby;	/* optional element of type xsd:string */
	int offset;	/* required element of type xsd:int */
	int limit;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__set_USCOREentryResponse
#define SOAP_TYPE_ns1__set_USCOREentryResponse (160)
/* ns1:set_entryResponse */
struct ns1__set_USCOREentryResponse
{
	struct ns1__new_USCOREset_USCOREentry_USCOREresult *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:new_set_entry_result */
};
#endif

#ifndef SOAP_TYPE_ns1__set_USCOREentry
#define SOAP_TYPE_ns1__set_USCOREentry (164)
/* ns1:set_entry */
struct ns1__set_USCOREentry
{
	char *session;	/* optional element of type xsd:string */
	char *module_USCOREname;	/* optional element of type xsd:string */
	struct name_USCOREvalue_USCORElist *name_USCOREvalue_USCORElist;	/* optional element of type ArrayOfname-value */
};
#endif

#ifndef SOAP_TYPE_ns1__set_USCOREentriesResponse
#define SOAP_TYPE_ns1__set_USCOREentriesResponse (165)
/* ns1:set_entriesResponse */
struct ns1__set_USCOREentriesResponse
{
	struct ns1__new_USCOREset_USCOREentries_USCOREresult *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:new_set_entries_result */
};
#endif

#ifndef SOAP_TYPE_ns1__set_USCOREentries
#define SOAP_TYPE_ns1__set_USCOREentries (169)
/* ns1:set_entries */
struct ns1__set_USCOREentries
{
	char *session;	/* optional element of type xsd:string */
	char *module_USCOREname;	/* optional element of type xsd:string */
	struct name_USCOREvalue_USCORElists *name_USCOREvalue_USCORElists;	/* optional element of type ArrayOfArrayOfname-value */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREserver_USCOREinfoResponse
#define SOAP_TYPE_ns1__get_USCOREserver_USCOREinfoResponse (170)
/* ns1:get_server_infoResponse */
struct ns1__get_USCOREserver_USCOREinfoResponse
{
	struct ns1__get_USCOREserver_USCOREinfo_USCOREresult *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:get_server_info_result */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREserver_USCOREinfo
#define SOAP_TYPE_ns1__get_USCOREserver_USCOREinfo (174)
/* ns1:get_server_info */
struct ns1__get_USCOREserver_USCOREinfo
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREuser_USCOREidResponse
#define SOAP_TYPE_ns1__get_USCOREuser_USCOREidResponse (176)
/* ns1:get_user_idResponse */
struct ns1__get_USCOREuser_USCOREidResponse
{
	char **return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREuser_USCOREid
#define SOAP_TYPE_ns1__get_USCOREuser_USCOREid (177)
/* ns1:get_user_id */
struct ns1__get_USCOREuser_USCOREid
{
	char *session;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREmodule_USCOREfieldsResponse
#define SOAP_TYPE_ns1__get_USCOREmodule_USCOREfieldsResponse (178)
/* ns1:get_module_fieldsResponse */
struct ns1__get_USCOREmodule_USCOREfieldsResponse
{
	struct ns1__new_USCOREmodule_USCOREfields *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:new_module_fields */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREmodule_USCOREfields
#define SOAP_TYPE_ns1__get_USCOREmodule_USCOREfields (182)
/* ns1:get_module_fields */
struct ns1__get_USCOREmodule_USCOREfields
{
	char *session;	/* optional element of type xsd:string */
	char *module_USCOREname;	/* optional element of type xsd:string */
	struct select_USCOREfields *fields;	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__seamless_USCOREloginResponse
#define SOAP_TYPE_ns1__seamless_USCOREloginResponse (184)
/* ns1:seamless_loginResponse */
struct ns1__seamless_USCOREloginResponse
{
	int *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__seamless_USCORElogin
#define SOAP_TYPE_ns1__seamless_USCORElogin (185)
/* ns1:seamless_login */
struct ns1__seamless_USCORElogin
{
	char *session;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__set_USCOREnote_USCOREattachmentResponse
#define SOAP_TYPE_ns1__set_USCOREnote_USCOREattachmentResponse (186)
/* ns1:set_note_attachmentResponse */
struct ns1__set_USCOREnote_USCOREattachmentResponse
{
	struct ns1__new_USCOREset_USCOREentry_USCOREresult *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:new_set_entry_result */
};
#endif

#ifndef SOAP_TYPE_ns1__set_USCOREnote_USCOREattachment
#define SOAP_TYPE_ns1__set_USCOREnote_USCOREattachment (189)
/* ns1:set_note_attachment */
struct ns1__set_USCOREnote_USCOREattachment
{
	char *session;	/* optional element of type xsd:string */
	struct ns1__new_USCOREnote_USCOREattachment *note;	/* optional element of type ns1:new_note_attachment */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREnote_USCOREattachmentResponse
#define SOAP_TYPE_ns1__get_USCOREnote_USCOREattachmentResponse (190)
/* ns1:get_note_attachmentResponse */
struct ns1__get_USCOREnote_USCOREattachmentResponse
{
	struct ns1__new_USCOREreturn_USCOREnote_USCOREattachment *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:new_return_note_attachment */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREnote_USCOREattachment
#define SOAP_TYPE_ns1__get_USCOREnote_USCOREattachment (194)
/* ns1:get_note_attachment */
struct ns1__get_USCOREnote_USCOREattachment
{
	char *session;	/* optional element of type xsd:string */
	char *id;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__set_USCOREdocument_USCORErevisionResponse
#define SOAP_TYPE_ns1__set_USCOREdocument_USCORErevisionResponse (195)
/* ns1:set_document_revisionResponse */
struct ns1__set_USCOREdocument_USCORErevisionResponse
{
	struct ns1__new_USCOREset_USCOREentry_USCOREresult *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:new_set_entry_result */
};
#endif

#ifndef SOAP_TYPE_ns1__set_USCOREdocument_USCORErevision
#define SOAP_TYPE_ns1__set_USCOREdocument_USCORErevision (198)
/* ns1:set_document_revision */
struct ns1__set_USCOREdocument_USCORErevision
{
	char *session;	/* optional element of type xsd:string */
	struct ns1__document_USCORErevision *note;	/* optional element of type ns1:document_revision */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREdocument_USCORErevisionResponse
#define SOAP_TYPE_ns1__get_USCOREdocument_USCORErevisionResponse (199)
/* ns1:get_document_revisionResponse */
struct ns1__get_USCOREdocument_USCORErevisionResponse
{
	struct ns1__new_USCOREreturn_USCOREdocument_USCORErevision *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:new_return_document_revision */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREdocument_USCORErevision
#define SOAP_TYPE_ns1__get_USCOREdocument_USCORErevision (203)
/* ns1:get_document_revision */
struct ns1__get_USCOREdocument_USCORErevision
{
	char *session;	/* optional element of type xsd:string */
	char *i;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__search_USCOREby_USCOREmoduleResponse
#define SOAP_TYPE_ns1__search_USCOREby_USCOREmoduleResponse (204)
/* ns1:search_by_moduleResponse */
struct ns1__search_USCOREby_USCOREmoduleResponse
{
	struct ns1__return_USCOREsearch_USCOREresult *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:return_search_result */
};
#endif

#ifndef SOAP_TYPE_ns1__search_USCOREby_USCOREmodule
#define SOAP_TYPE_ns1__search_USCOREby_USCOREmodule (208)
/* ns1:search_by_module */
struct ns1__search_USCOREby_USCOREmodule
{
	char *session;	/* optional element of type xsd:string */
	char *search_USCOREstring;	/* optional element of type xsd:string */
	struct select_USCOREfields *modules;	/* optional element of type ArrayOfstring */
	int offset;	/* required element of type xsd:int */
	int max_USCOREresults;	/* required element of type xsd:int */
	char *assigned_USCOREuser_USCOREid;	/* optional element of type xsd:string */
	struct select_USCOREfields *select_USCOREfields;	/* optional element of type ArrayOfstring */
	enum xsd__boolean unified_USCOREsearch_USCOREonly;	/* required element of type xsd:boolean */
	enum xsd__boolean favorites;	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREavailable_USCOREmodulesResponse
#define SOAP_TYPE_ns1__get_USCOREavailable_USCOREmodulesResponse (209)
/* ns1:get_available_modulesResponse */
struct ns1__get_USCOREavailable_USCOREmodulesResponse
{
	struct ns1__module_USCORElist *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:module_list */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREavailable_USCOREmodules
#define SOAP_TYPE_ns1__get_USCOREavailable_USCOREmodules (213)
/* ns1:get_available_modules */
struct ns1__get_USCOREavailable_USCOREmodules
{
	char *session;	/* optional element of type xsd:string */
	char *filter;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREuser_USCOREteam_USCOREidResponse
#define SOAP_TYPE_ns1__get_USCOREuser_USCOREteam_USCOREidResponse (215)
/* ns1:get_user_team_idResponse */
struct ns1__get_USCOREuser_USCOREteam_USCOREidResponse
{
	char **return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREuser_USCOREteam_USCOREid
#define SOAP_TYPE_ns1__get_USCOREuser_USCOREteam_USCOREid (216)
/* ns1:get_user_team_id */
struct ns1__get_USCOREuser_USCOREteam_USCOREid
{
	char *session;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__set_USCOREcampaign_USCOREmergeResponse
#define SOAP_TYPE_ns1__set_USCOREcampaign_USCOREmergeResponse (217)
/* ns1:set_campaign_mergeResponse */
struct ns1__set_USCOREcampaign_USCOREmergeResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_ns1__set_USCOREcampaign_USCOREmerge
#define SOAP_TYPE_ns1__set_USCOREcampaign_USCOREmerge (220)
/* ns1:set_campaign_merge */
struct ns1__set_USCOREcampaign_USCOREmerge
{
	char *session;	/* optional element of type xsd:string */
	struct select_USCOREfields *targets;	/* optional element of type ArrayOfstring */
	char *campaign_USCOREid;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREentries_USCOREcountResponse
#define SOAP_TYPE_ns1__get_USCOREentries_USCOREcountResponse (221)
/* ns1:get_entries_countResponse */
struct ns1__get_USCOREentries_USCOREcountResponse
{
	struct ns1__get_USCOREentries_USCOREcount_USCOREresult *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:get_entries_count_result */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREentries_USCOREcount
#define SOAP_TYPE_ns1__get_USCOREentries_USCOREcount (225)
/* ns1:get_entries_count */
struct ns1__get_USCOREentries_USCOREcount
{
	char *session;	/* optional element of type xsd:string */
	char *module_USCOREname;	/* optional element of type xsd:string */
	char *query;	/* optional element of type xsd:string */
	int deleted;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREmodule_USCOREfields_USCOREmd5Response
#define SOAP_TYPE_ns1__get_USCOREmodule_USCOREfields_USCOREmd5Response (226)
/* ns1:get_module_fields_md5Response */
struct ns1__get_USCOREmodule_USCOREfields_USCOREmd5Response
{
	struct md5_USCOREresults *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREmodule_USCOREfields_USCOREmd5
#define SOAP_TYPE_ns1__get_USCOREmodule_USCOREfields_USCOREmd5 (230)
/* ns1:get_module_fields_md5 */
struct ns1__get_USCOREmodule_USCOREfields_USCOREmd5
{
	char *session;	/* optional element of type xsd:string */
	struct select_USCOREfields *module_USCOREnames;	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCORElast_USCOREviewedResponse
#define SOAP_TYPE_ns1__get_USCORElast_USCOREviewedResponse (231)
/* ns1:get_last_viewedResponse */
struct ns1__get_USCORElast_USCOREviewedResponse
{
	struct last_USCOREviewed_USCORElist *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOflast-viewed-entry */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCORElast_USCOREviewed
#define SOAP_TYPE_ns1__get_USCORElast_USCOREviewed (236)
/* ns1:get_last_viewed */
struct ns1__get_USCORElast_USCOREviewed
{
	char *session;	/* optional element of type xsd:string */
	struct module_USCOREnames *module_USCOREnames;	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREupcoming_USCOREactivitiesResponse
#define SOAP_TYPE_ns1__get_USCOREupcoming_USCOREactivitiesResponse (237)
/* ns1:get_upcoming_activitiesResponse */
struct ns1__get_USCOREupcoming_USCOREactivitiesResponse
{
	struct upcoming_USCOREactivities_USCORElist *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfupcoming-activity-entry */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREupcoming_USCOREactivities
#define SOAP_TYPE_ns1__get_USCOREupcoming_USCOREactivities (241)
/* ns1:get_upcoming_activities */
struct ns1__get_USCOREupcoming_USCOREactivities
{
	char *session;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREmodified_USCORErelationshipsResponse
#define SOAP_TYPE_ns1__get_USCOREmodified_USCORErelationshipsResponse (242)
/* ns1:get_modified_relationshipsResponse */
struct ns1__get_USCOREmodified_USCORErelationshipsResponse
{
	struct ns1__modified_USCORErelationship_USCOREresult *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:modified_relationship_result */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREmodified_USCORErelationships
#define SOAP_TYPE_ns1__get_USCOREmodified_USCORErelationships (246)
/* ns1:get_modified_relationships */
struct ns1__get_USCOREmodified_USCORErelationships
{
	char *session;	/* optional element of type xsd:string */
	char *module_USCOREname;	/* optional element of type xsd:string */
	char *related_USCOREmodule;	/* optional element of type xsd:string */
	char *from_USCOREdate;	/* optional element of type xsd:string */
	char *to_USCOREdate;	/* optional element of type xsd:string */
	int offset;	/* required element of type xsd:int */
	int max_USCOREresults;	/* required element of type xsd:int */
	int deleted;	/* required element of type xsd:int */
	char *module_USCOREuser_USCOREid;	/* optional element of type xsd:string */
	struct select_USCOREfields *select_USCOREfields;	/* optional element of type ArrayOfstring */
	char *relationship_USCOREname;	/* optional element of type xsd:string */
	char *deletion_USCOREdate;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (247)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (248)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (250)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
	char *__any;
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (253)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (254)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__login(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__user_USCOREauth *user_USCOREauth, char *application_USCOREname, struct name_USCOREvalue_USCORElist *name_USCOREvalue_USCORElist, struct ns1__loginResponse *_param_1);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__logout(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, struct ns1__logoutResponse *_param_2);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREentry(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *module_USCOREname, char *id, struct select_USCOREfields *select_USCOREfields, struct link_USCOREnames_USCOREto_USCOREfields_USCOREarray *link_USCOREname_USCOREto_USCOREfields_USCOREarray, enum xsd__boolean track_USCOREview, struct ns1__get_USCOREentryResponse *_param_3);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREentries(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *module_USCOREname, struct select_USCOREfields *ids, struct select_USCOREfields *select_USCOREfields, struct link_USCOREnames_USCOREto_USCOREfields_USCOREarray *link_USCOREname_USCOREto_USCOREfields_USCOREarray, enum xsd__boolean track_USCOREview, struct ns1__get_USCOREentriesResponse *_param_4);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREentry_USCORElist(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *module_USCOREname, char *query, char *order_USCOREby, int offset, struct select_USCOREfields *select_USCOREfields, struct link_USCOREnames_USCOREto_USCOREfields_USCOREarray *link_USCOREname_USCOREto_USCOREfields_USCOREarray, int max_USCOREresults, int deleted, enum xsd__boolean favorites, struct ns1__get_USCOREentry_USCORElistResponse *_param_5);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__set_USCORErelationship(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *module_USCOREname, char *module_USCOREid, char *link_USCOREfield_USCOREname, struct select_USCOREfields *related_USCOREids, struct name_USCOREvalue_USCORElist *name_USCOREvalue_USCORElist, int delete_, struct ns1__set_USCORErelationshipResponse *_param_6);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__set_USCORErelationships(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, struct select_USCOREfields *module_USCOREnames, struct select_USCOREfields *module_USCOREids, struct select_USCOREfields *link_USCOREfield_USCOREnames, struct new_USCOREset_USCORErelationhip_USCOREids *related_USCOREids, struct name_USCOREvalue_USCORElists *name_USCOREvalue_USCORElists, struct deleted_USCOREarray *delete_USCOREarray, struct ns1__set_USCORErelationshipsResponse *_param_7);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCORErelationships(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *module_USCOREname, char *module_USCOREid, char *link_USCOREfield_USCOREname, char *related_USCOREmodule_USCOREquery, struct select_USCOREfields *related_USCOREfields, struct link_USCOREnames_USCOREto_USCOREfields_USCOREarray *related_USCOREmodule_USCORElink_USCOREname_USCOREto_USCOREfields_USCOREarray, int deleted, char *order_USCOREby, int offset, int limit, struct ns1__get_USCORErelationshipsResponse *_param_8);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__set_USCOREentry(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *module_USCOREname, struct name_USCOREvalue_USCORElist *name_USCOREvalue_USCORElist, struct ns1__set_USCOREentryResponse *_param_9);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__set_USCOREentries(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *module_USCOREname, struct name_USCOREvalue_USCORElists *name_USCOREvalue_USCORElists, struct ns1__set_USCOREentriesResponse *_param_10);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREserver_USCOREinfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__get_USCOREserver_USCOREinfoResponse *_param_11);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREuser_USCOREid(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREmodule_USCOREfields(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *module_USCOREname, struct select_USCOREfields *fields, struct ns1__get_USCOREmodule_USCOREfieldsResponse *_param_12);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__seamless_USCORElogin(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, int *return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__set_USCOREnote_USCOREattachment(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, struct ns1__new_USCOREnote_USCOREattachment *note, struct ns1__set_USCOREnote_USCOREattachmentResponse *_param_13);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREnote_USCOREattachment(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *id, struct ns1__get_USCOREnote_USCOREattachmentResponse *_param_14);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__set_USCOREdocument_USCORErevision(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, struct ns1__document_USCORErevision *note, struct ns1__set_USCOREdocument_USCORErevisionResponse *_param_15);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREdocument_USCORErevision(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *i, struct ns1__get_USCOREdocument_USCORErevisionResponse *_param_16);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__search_USCOREby_USCOREmodule(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *search_USCOREstring, struct select_USCOREfields *modules, int offset, int max_USCOREresults, char *assigned_USCOREuser_USCOREid, struct select_USCOREfields *select_USCOREfields, enum xsd__boolean unified_USCOREsearch_USCOREonly, enum xsd__boolean favorites, struct ns1__search_USCOREby_USCOREmoduleResponse *_param_17);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREavailable_USCOREmodules(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *filter, struct ns1__get_USCOREavailable_USCOREmodulesResponse *_param_18);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREuser_USCOREteam_USCOREid(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__set_USCOREcampaign_USCOREmerge(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, struct select_USCOREfields *targets, char *campaign_USCOREid, struct ns1__set_USCOREcampaign_USCOREmergeResponse *_param_19);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREentries_USCOREcount(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *module_USCOREname, char *query, int deleted, struct ns1__get_USCOREentries_USCOREcountResponse *_param_20);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREmodule_USCOREfields_USCOREmd5(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, struct select_USCOREfields *module_USCOREnames, struct ns1__get_USCOREmodule_USCOREfields_USCOREmd5Response *_param_21);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCORElast_USCOREviewed(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, struct module_USCOREnames *module_USCOREnames, struct ns1__get_USCORElast_USCOREviewedResponse *_param_22);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREupcoming_USCOREactivities(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, struct ns1__get_USCOREupcoming_USCOREactivitiesResponse *_param_23);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREmodified_USCORErelationships(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *module_USCOREname, char *related_USCOREmodule, char *from_USCOREdate, char *to_USCOREdate, int offset, int max_USCOREresults, int deleted, char *module_USCOREuser_USCOREid, struct select_USCOREfields *select_USCOREfields, char *relationship_USCOREname, char *deletion_USCOREdate, struct ns1__get_USCOREmodified_USCORErelationshipsResponse *_param_24);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
