/* soapClient.c
   Generated by gSOAP 2.7.16 from sugar_soap.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "sugar_soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.7.16 2016-05-16 11:56:51 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__login(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__user_USCOREauth *user_USCOREauth, char *application_USCOREname, struct name_USCOREvalue_USCORElist *name_USCOREvalue_USCORElist, struct ns1__loginResponse *_param_1)
{	struct ns1__login soap_tmp_ns1__login;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.124.27/crm/service/v4_1/soap.php";
	if (!soap_action)
		soap_action = "http://192.168.124.27/crm/service/v4_1/soap.php/login";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__login.user_USCOREauth = user_USCOREauth;
	soap_tmp_ns1__login.application_USCOREname = application_USCOREname;
	soap_tmp_ns1__login.name_USCOREvalue_USCORElist = name_USCOREvalue_USCORElist;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__login(soap, &soap_tmp_ns1__login);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__login(soap, &soap_tmp_ns1__login, "ns1:login", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__login(soap, &soap_tmp_ns1__login, "ns1:login", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_1)
		return soap_closesock(soap);
	soap_default_ns1__loginResponse(soap, _param_1);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__loginResponse(soap, _param_1, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__logout(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, struct ns1__logoutResponse *_param_2)
{	struct ns1__logout soap_tmp_ns1__logout;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.124.27/crm/service/v4_1/soap.php";
	if (!soap_action)
		soap_action = "http://192.168.124.27/crm/service/v4_1/soap.php/logout";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__logout.session = session;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__logout(soap, &soap_tmp_ns1__logout);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__logout(soap, &soap_tmp_ns1__logout, "ns1:logout", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__logout(soap, &soap_tmp_ns1__logout, "ns1:logout", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_2)
		return soap_closesock(soap);
	soap_default_ns1__logoutResponse(soap, _param_2);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__logoutResponse(soap, _param_2, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREentry(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *module_USCOREname, char *id, struct select_USCOREfields *select_USCOREfields, struct link_USCOREnames_USCOREto_USCOREfields_USCOREarray *link_USCOREname_USCOREto_USCOREfields_USCOREarray, enum xsd__boolean track_USCOREview, struct ns1__get_USCOREentryResponse *_param_3)
{	struct ns1__get_USCOREentry soap_tmp_ns1__get_USCOREentry;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.124.27/crm/service/v4_1/soap.php";
	if (!soap_action)
		soap_action = "http://192.168.124.27/crm/service/v4_1/soap.php/get_entry";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__get_USCOREentry.session = session;
	soap_tmp_ns1__get_USCOREentry.module_USCOREname = module_USCOREname;
	soap_tmp_ns1__get_USCOREentry.id = id;
	soap_tmp_ns1__get_USCOREentry.select_USCOREfields = select_USCOREfields;
	soap_tmp_ns1__get_USCOREentry.link_USCOREname_USCOREto_USCOREfields_USCOREarray = link_USCOREname_USCOREto_USCOREfields_USCOREarray;
	soap_tmp_ns1__get_USCOREentry.track_USCOREview = track_USCOREview;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__get_USCOREentry(soap, &soap_tmp_ns1__get_USCOREentry);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__get_USCOREentry(soap, &soap_tmp_ns1__get_USCOREentry, "ns1:get_entry", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__get_USCOREentry(soap, &soap_tmp_ns1__get_USCOREentry, "ns1:get_entry", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_3)
		return soap_closesock(soap);
	soap_default_ns1__get_USCOREentryResponse(soap, _param_3);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__get_USCOREentryResponse(soap, _param_3, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREentries(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *module_USCOREname, struct select_USCOREfields *ids, struct select_USCOREfields *select_USCOREfields, struct link_USCOREnames_USCOREto_USCOREfields_USCOREarray *link_USCOREname_USCOREto_USCOREfields_USCOREarray, enum xsd__boolean track_USCOREview, struct ns1__get_USCOREentriesResponse *_param_4)
{	struct ns1__get_USCOREentries soap_tmp_ns1__get_USCOREentries;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.124.27/crm/service/v4_1/soap.php";
	if (!soap_action)
		soap_action = "http://192.168.124.27/crm/service/v4_1/soap.php/get_entries";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__get_USCOREentries.session = session;
	soap_tmp_ns1__get_USCOREentries.module_USCOREname = module_USCOREname;
	soap_tmp_ns1__get_USCOREentries.ids = ids;
	soap_tmp_ns1__get_USCOREentries.select_USCOREfields = select_USCOREfields;
	soap_tmp_ns1__get_USCOREentries.link_USCOREname_USCOREto_USCOREfields_USCOREarray = link_USCOREname_USCOREto_USCOREfields_USCOREarray;
	soap_tmp_ns1__get_USCOREentries.track_USCOREview = track_USCOREview;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__get_USCOREentries(soap, &soap_tmp_ns1__get_USCOREentries);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__get_USCOREentries(soap, &soap_tmp_ns1__get_USCOREentries, "ns1:get_entries", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__get_USCOREentries(soap, &soap_tmp_ns1__get_USCOREentries, "ns1:get_entries", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_4)
		return soap_closesock(soap);
	soap_default_ns1__get_USCOREentriesResponse(soap, _param_4);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__get_USCOREentriesResponse(soap, _param_4, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREentry_USCORElist(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *module_USCOREname, char *query, char *order_USCOREby, int offset, struct select_USCOREfields *select_USCOREfields, struct link_USCOREnames_USCOREto_USCOREfields_USCOREarray *link_USCOREname_USCOREto_USCOREfields_USCOREarray, int max_USCOREresults, int deleted, enum xsd__boolean favorites, struct ns1__get_USCOREentry_USCORElistResponse *_param_5)
{	struct ns1__get_USCOREentry_USCORElist soap_tmp_ns1__get_USCOREentry_USCORElist;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.124.27/crm/service/v4_1/soap.php";
	if (!soap_action)
		soap_action = "http://192.168.124.27/crm/service/v4_1/soap.php/get_entry_list";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__get_USCOREentry_USCORElist.session = session;
	soap_tmp_ns1__get_USCOREentry_USCORElist.module_USCOREname = module_USCOREname;
	soap_tmp_ns1__get_USCOREentry_USCORElist.query = query;
	soap_tmp_ns1__get_USCOREentry_USCORElist.order_USCOREby = order_USCOREby;
	soap_tmp_ns1__get_USCOREentry_USCORElist.offset = offset;
	soap_tmp_ns1__get_USCOREentry_USCORElist.select_USCOREfields = select_USCOREfields;
	soap_tmp_ns1__get_USCOREentry_USCORElist.link_USCOREname_USCOREto_USCOREfields_USCOREarray = link_USCOREname_USCOREto_USCOREfields_USCOREarray;
	soap_tmp_ns1__get_USCOREentry_USCORElist.max_USCOREresults = max_USCOREresults;
	soap_tmp_ns1__get_USCOREentry_USCORElist.deleted = deleted;
	soap_tmp_ns1__get_USCOREentry_USCORElist.favorites = favorites;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__get_USCOREentry_USCORElist(soap, &soap_tmp_ns1__get_USCOREentry_USCORElist);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__get_USCOREentry_USCORElist(soap, &soap_tmp_ns1__get_USCOREentry_USCORElist, "ns1:get_entry_list", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__get_USCOREentry_USCORElist(soap, &soap_tmp_ns1__get_USCOREentry_USCORElist, "ns1:get_entry_list", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_5)
		return soap_closesock(soap);
	soap_default_ns1__get_USCOREentry_USCORElistResponse(soap, _param_5);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__get_USCOREentry_USCORElistResponse(soap, _param_5, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__set_USCORErelationship(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *module_USCOREname, char *module_USCOREid, char *link_USCOREfield_USCOREname, struct select_USCOREfields *related_USCOREids, struct name_USCOREvalue_USCORElist *name_USCOREvalue_USCORElist, int delete_, struct ns1__set_USCORErelationshipResponse *_param_6)
{	struct ns1__set_USCORErelationship soap_tmp_ns1__set_USCORErelationship;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.124.27/crm/service/v4_1/soap.php";
	if (!soap_action)
		soap_action = "http://192.168.124.27/crm/service/v4_1/soap.php/set_relationship";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__set_USCORErelationship.session = session;
	soap_tmp_ns1__set_USCORErelationship.module_USCOREname = module_USCOREname;
	soap_tmp_ns1__set_USCORErelationship.module_USCOREid = module_USCOREid;
	soap_tmp_ns1__set_USCORErelationship.link_USCOREfield_USCOREname = link_USCOREfield_USCOREname;
	soap_tmp_ns1__set_USCORErelationship.related_USCOREids = related_USCOREids;
	soap_tmp_ns1__set_USCORErelationship.name_USCOREvalue_USCORElist = name_USCOREvalue_USCORElist;
	soap_tmp_ns1__set_USCORErelationship.delete_ = delete_;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__set_USCORErelationship(soap, &soap_tmp_ns1__set_USCORErelationship);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__set_USCORErelationship(soap, &soap_tmp_ns1__set_USCORErelationship, "ns1:set_relationship", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__set_USCORErelationship(soap, &soap_tmp_ns1__set_USCORErelationship, "ns1:set_relationship", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_6)
		return soap_closesock(soap);
	soap_default_ns1__set_USCORErelationshipResponse(soap, _param_6);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__set_USCORErelationshipResponse(soap, _param_6, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__set_USCORErelationships(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, struct select_USCOREfields *module_USCOREnames, struct select_USCOREfields *module_USCOREids, struct select_USCOREfields *link_USCOREfield_USCOREnames, struct new_USCOREset_USCORErelationhip_USCOREids *related_USCOREids, struct name_USCOREvalue_USCORElists *name_USCOREvalue_USCORElists, struct deleted_USCOREarray *delete_USCOREarray, struct ns1__set_USCORErelationshipsResponse *_param_7)
{	struct ns1__set_USCORErelationships soap_tmp_ns1__set_USCORErelationships;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.124.27/crm/service/v4_1/soap.php";
	if (!soap_action)
		soap_action = "http://192.168.124.27/crm/service/v4_1/soap.php/set_relationships";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__set_USCORErelationships.session = session;
	soap_tmp_ns1__set_USCORErelationships.module_USCOREnames = module_USCOREnames;
	soap_tmp_ns1__set_USCORErelationships.module_USCOREids = module_USCOREids;
	soap_tmp_ns1__set_USCORErelationships.link_USCOREfield_USCOREnames = link_USCOREfield_USCOREnames;
	soap_tmp_ns1__set_USCORErelationships.related_USCOREids = related_USCOREids;
	soap_tmp_ns1__set_USCORErelationships.name_USCOREvalue_USCORElists = name_USCOREvalue_USCORElists;
	soap_tmp_ns1__set_USCORErelationships.delete_USCOREarray = delete_USCOREarray;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__set_USCORErelationships(soap, &soap_tmp_ns1__set_USCORErelationships);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__set_USCORErelationships(soap, &soap_tmp_ns1__set_USCORErelationships, "ns1:set_relationships", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__set_USCORErelationships(soap, &soap_tmp_ns1__set_USCORErelationships, "ns1:set_relationships", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_7)
		return soap_closesock(soap);
	soap_default_ns1__set_USCORErelationshipsResponse(soap, _param_7);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__set_USCORErelationshipsResponse(soap, _param_7, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCORErelationships(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *module_USCOREname, char *module_USCOREid, char *link_USCOREfield_USCOREname, char *related_USCOREmodule_USCOREquery, struct select_USCOREfields *related_USCOREfields, struct link_USCOREnames_USCOREto_USCOREfields_USCOREarray *related_USCOREmodule_USCORElink_USCOREname_USCOREto_USCOREfields_USCOREarray, int deleted, char *order_USCOREby, int offset, int limit, struct ns1__get_USCORErelationshipsResponse *_param_8)
{	struct ns1__get_USCORErelationships soap_tmp_ns1__get_USCORErelationships;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.124.27/crm/service/v4_1/soap.php";
	if (!soap_action)
		soap_action = "http://192.168.124.27/crm/service/v4_1/soap.php/get_relationships";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__get_USCORErelationships.session = session;
	soap_tmp_ns1__get_USCORErelationships.module_USCOREname = module_USCOREname;
	soap_tmp_ns1__get_USCORErelationships.module_USCOREid = module_USCOREid;
	soap_tmp_ns1__get_USCORErelationships.link_USCOREfield_USCOREname = link_USCOREfield_USCOREname;
	soap_tmp_ns1__get_USCORErelationships.related_USCOREmodule_USCOREquery = related_USCOREmodule_USCOREquery;
	soap_tmp_ns1__get_USCORErelationships.related_USCOREfields = related_USCOREfields;
	soap_tmp_ns1__get_USCORErelationships.related_USCOREmodule_USCORElink_USCOREname_USCOREto_USCOREfields_USCOREarray = related_USCOREmodule_USCORElink_USCOREname_USCOREto_USCOREfields_USCOREarray;
	soap_tmp_ns1__get_USCORErelationships.deleted = deleted;
	soap_tmp_ns1__get_USCORErelationships.order_USCOREby = order_USCOREby;
	soap_tmp_ns1__get_USCORErelationships.offset = offset;
	soap_tmp_ns1__get_USCORErelationships.limit = limit;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__get_USCORErelationships(soap, &soap_tmp_ns1__get_USCORErelationships);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__get_USCORErelationships(soap, &soap_tmp_ns1__get_USCORErelationships, "ns1:get_relationships", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__get_USCORErelationships(soap, &soap_tmp_ns1__get_USCORErelationships, "ns1:get_relationships", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_8)
		return soap_closesock(soap);
	soap_default_ns1__get_USCORErelationshipsResponse(soap, _param_8);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__get_USCORErelationshipsResponse(soap, _param_8, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__set_USCOREentry(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *module_USCOREname, struct name_USCOREvalue_USCORElist *name_USCOREvalue_USCORElist, struct ns1__set_USCOREentryResponse *_param_9)
{	struct ns1__set_USCOREentry soap_tmp_ns1__set_USCOREentry;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.124.27/crm/service/v4_1/soap.php";
	if (!soap_action)
		soap_action = "http://192.168.124.27/crm/service/v4_1/soap.php/set_entry";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__set_USCOREentry.session = session;
	soap_tmp_ns1__set_USCOREentry.module_USCOREname = module_USCOREname;
	soap_tmp_ns1__set_USCOREentry.name_USCOREvalue_USCORElist = name_USCOREvalue_USCORElist;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__set_USCOREentry(soap, &soap_tmp_ns1__set_USCOREentry);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__set_USCOREentry(soap, &soap_tmp_ns1__set_USCOREentry, "ns1:set_entry", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__set_USCOREentry(soap, &soap_tmp_ns1__set_USCOREentry, "ns1:set_entry", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_9)
		return soap_closesock(soap);
	soap_default_ns1__set_USCOREentryResponse(soap, _param_9);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__set_USCOREentryResponse(soap, _param_9, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__set_USCOREentries(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *module_USCOREname, struct name_USCOREvalue_USCORElists *name_USCOREvalue_USCORElists, struct ns1__set_USCOREentriesResponse *_param_10)
{	struct ns1__set_USCOREentries soap_tmp_ns1__set_USCOREentries;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.124.27/crm/service/v4_1/soap.php";
	if (!soap_action)
		soap_action = "http://192.168.124.27/crm/service/v4_1/soap.php/set_entries";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__set_USCOREentries.session = session;
	soap_tmp_ns1__set_USCOREentries.module_USCOREname = module_USCOREname;
	soap_tmp_ns1__set_USCOREentries.name_USCOREvalue_USCORElists = name_USCOREvalue_USCORElists;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__set_USCOREentries(soap, &soap_tmp_ns1__set_USCOREentries);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__set_USCOREentries(soap, &soap_tmp_ns1__set_USCOREentries, "ns1:set_entries", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__set_USCOREentries(soap, &soap_tmp_ns1__set_USCOREentries, "ns1:set_entries", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_10)
		return soap_closesock(soap);
	soap_default_ns1__set_USCOREentriesResponse(soap, _param_10);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__set_USCOREentriesResponse(soap, _param_10, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREserver_USCOREinfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__get_USCOREserver_USCOREinfoResponse *_param_11)
{	struct ns1__get_USCOREserver_USCOREinfo soap_tmp_ns1__get_USCOREserver_USCOREinfo;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.124.27/crm/service/v4_1/soap.php";
	if (!soap_action)
		soap_action = "http://192.168.124.27/crm/service/v4_1/soap.php/get_server_info";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__get_USCOREserver_USCOREinfo(soap, &soap_tmp_ns1__get_USCOREserver_USCOREinfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__get_USCOREserver_USCOREinfo(soap, &soap_tmp_ns1__get_USCOREserver_USCOREinfo, "ns1:get_server_info", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__get_USCOREserver_USCOREinfo(soap, &soap_tmp_ns1__get_USCOREserver_USCOREinfo, "ns1:get_server_info", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_11)
		return soap_closesock(soap);
	soap_default_ns1__get_USCOREserver_USCOREinfoResponse(soap, _param_11);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__get_USCOREserver_USCOREinfoResponse(soap, _param_11, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREuser_USCOREid(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char **return_)
{	struct ns1__get_USCOREuser_USCOREid soap_tmp_ns1__get_USCOREuser_USCOREid;
	struct ns1__get_USCOREuser_USCOREidResponse *soap_tmp_ns1__get_USCOREuser_USCOREidResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.124.27/crm/service/v4_1/soap.php";
	if (!soap_action)
		soap_action = "http://192.168.124.27/crm/service/v4_1/soap.php/get_user_id";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__get_USCOREuser_USCOREid.session = session;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__get_USCOREuser_USCOREid(soap, &soap_tmp_ns1__get_USCOREuser_USCOREid);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__get_USCOREuser_USCOREid(soap, &soap_tmp_ns1__get_USCOREuser_USCOREid, "ns1:get_user_id", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__get_USCOREuser_USCOREid(soap, &soap_tmp_ns1__get_USCOREuser_USCOREid, "ns1:get_user_id", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!return_)
		return soap_closesock(soap);
	*return_ = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__get_USCOREuser_USCOREidResponse = soap_get_ns1__get_USCOREuser_USCOREidResponse(soap, NULL, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (return_ && soap_tmp_ns1__get_USCOREuser_USCOREidResponse->return_)
		*return_ = *soap_tmp_ns1__get_USCOREuser_USCOREidResponse->return_;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREmodule_USCOREfields(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *module_USCOREname, struct select_USCOREfields *fields, struct ns1__get_USCOREmodule_USCOREfieldsResponse *_param_12)
{	struct ns1__get_USCOREmodule_USCOREfields soap_tmp_ns1__get_USCOREmodule_USCOREfields;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.124.27/crm/service/v4_1/soap.php";
	if (!soap_action)
		soap_action = "http://192.168.124.27/crm/service/v4_1/soap.php/get_module_fields";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__get_USCOREmodule_USCOREfields.session = session;
	soap_tmp_ns1__get_USCOREmodule_USCOREfields.module_USCOREname = module_USCOREname;
	soap_tmp_ns1__get_USCOREmodule_USCOREfields.fields = fields;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__get_USCOREmodule_USCOREfields(soap, &soap_tmp_ns1__get_USCOREmodule_USCOREfields);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__get_USCOREmodule_USCOREfields(soap, &soap_tmp_ns1__get_USCOREmodule_USCOREfields, "ns1:get_module_fields", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__get_USCOREmodule_USCOREfields(soap, &soap_tmp_ns1__get_USCOREmodule_USCOREfields, "ns1:get_module_fields", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_12)
		return soap_closesock(soap);
	soap_default_ns1__get_USCOREmodule_USCOREfieldsResponse(soap, _param_12);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__get_USCOREmodule_USCOREfieldsResponse(soap, _param_12, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__seamless_USCORElogin(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, int *return_)
{	struct ns1__seamless_USCORElogin soap_tmp_ns1__seamless_USCORElogin;
	struct ns1__seamless_USCOREloginResponse *soap_tmp_ns1__seamless_USCOREloginResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.124.27/crm/service/v4_1/soap.php";
	if (!soap_action)
		soap_action = "http://192.168.124.27/crm/service/v4_1/soap.php/seamless_login";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__seamless_USCORElogin.session = session;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__seamless_USCORElogin(soap, &soap_tmp_ns1__seamless_USCORElogin);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__seamless_USCORElogin(soap, &soap_tmp_ns1__seamless_USCORElogin, "ns1:seamless_login", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__seamless_USCORElogin(soap, &soap_tmp_ns1__seamless_USCORElogin, "ns1:seamless_login", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!return_)
		return soap_closesock(soap);
	soap_default_int(soap, return_);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__seamless_USCOREloginResponse = soap_get_ns1__seamless_USCOREloginResponse(soap, NULL, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (return_ && soap_tmp_ns1__seamless_USCOREloginResponse->return_)
		*return_ = *soap_tmp_ns1__seamless_USCOREloginResponse->return_;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__set_USCOREnote_USCOREattachment(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, struct ns1__new_USCOREnote_USCOREattachment *note, struct ns1__set_USCOREnote_USCOREattachmentResponse *_param_13)
{	struct ns1__set_USCOREnote_USCOREattachment soap_tmp_ns1__set_USCOREnote_USCOREattachment;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.124.27/crm/service/v4_1/soap.php";
	if (!soap_action)
		soap_action = "http://192.168.124.27/crm/service/v4_1/soap.php/set_note_attachment";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__set_USCOREnote_USCOREattachment.session = session;
	soap_tmp_ns1__set_USCOREnote_USCOREattachment.note = note;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__set_USCOREnote_USCOREattachment(soap, &soap_tmp_ns1__set_USCOREnote_USCOREattachment);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__set_USCOREnote_USCOREattachment(soap, &soap_tmp_ns1__set_USCOREnote_USCOREattachment, "ns1:set_note_attachment", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__set_USCOREnote_USCOREattachment(soap, &soap_tmp_ns1__set_USCOREnote_USCOREattachment, "ns1:set_note_attachment", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_13)
		return soap_closesock(soap);
	soap_default_ns1__set_USCOREnote_USCOREattachmentResponse(soap, _param_13);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__set_USCOREnote_USCOREattachmentResponse(soap, _param_13, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREnote_USCOREattachment(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *id, struct ns1__get_USCOREnote_USCOREattachmentResponse *_param_14)
{	struct ns1__get_USCOREnote_USCOREattachment soap_tmp_ns1__get_USCOREnote_USCOREattachment;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.124.27/crm/service/v4_1/soap.php";
	if (!soap_action)
		soap_action = "http://192.168.124.27/crm/service/v4_1/soap.php/get_note_attachment";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__get_USCOREnote_USCOREattachment.session = session;
	soap_tmp_ns1__get_USCOREnote_USCOREattachment.id = id;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__get_USCOREnote_USCOREattachment(soap, &soap_tmp_ns1__get_USCOREnote_USCOREattachment);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__get_USCOREnote_USCOREattachment(soap, &soap_tmp_ns1__get_USCOREnote_USCOREattachment, "ns1:get_note_attachment", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__get_USCOREnote_USCOREattachment(soap, &soap_tmp_ns1__get_USCOREnote_USCOREattachment, "ns1:get_note_attachment", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_14)
		return soap_closesock(soap);
	soap_default_ns1__get_USCOREnote_USCOREattachmentResponse(soap, _param_14);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__get_USCOREnote_USCOREattachmentResponse(soap, _param_14, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__set_USCOREdocument_USCORErevision(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, struct ns1__document_USCORErevision *note, struct ns1__set_USCOREdocument_USCORErevisionResponse *_param_15)
{	struct ns1__set_USCOREdocument_USCORErevision soap_tmp_ns1__set_USCOREdocument_USCORErevision;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.124.27/crm/service/v4_1/soap.php";
	if (!soap_action)
		soap_action = "http://192.168.124.27/crm/service/v4_1/soap.php/set_document_revision";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__set_USCOREdocument_USCORErevision.session = session;
	soap_tmp_ns1__set_USCOREdocument_USCORErevision.note = note;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__set_USCOREdocument_USCORErevision(soap, &soap_tmp_ns1__set_USCOREdocument_USCORErevision);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__set_USCOREdocument_USCORErevision(soap, &soap_tmp_ns1__set_USCOREdocument_USCORErevision, "ns1:set_document_revision", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__set_USCOREdocument_USCORErevision(soap, &soap_tmp_ns1__set_USCOREdocument_USCORErevision, "ns1:set_document_revision", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_15)
		return soap_closesock(soap);
	soap_default_ns1__set_USCOREdocument_USCORErevisionResponse(soap, _param_15);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__set_USCOREdocument_USCORErevisionResponse(soap, _param_15, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREdocument_USCORErevision(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *i, struct ns1__get_USCOREdocument_USCORErevisionResponse *_param_16)
{	struct ns1__get_USCOREdocument_USCORErevision soap_tmp_ns1__get_USCOREdocument_USCORErevision;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.124.27/crm/service/v4_1/soap.php";
	if (!soap_action)
		soap_action = "http://192.168.124.27/crm/service/v4_1/soap.php/get_document_revision";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__get_USCOREdocument_USCORErevision.session = session;
	soap_tmp_ns1__get_USCOREdocument_USCORErevision.i = i;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__get_USCOREdocument_USCORErevision(soap, &soap_tmp_ns1__get_USCOREdocument_USCORErevision);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__get_USCOREdocument_USCORErevision(soap, &soap_tmp_ns1__get_USCOREdocument_USCORErevision, "ns1:get_document_revision", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__get_USCOREdocument_USCORErevision(soap, &soap_tmp_ns1__get_USCOREdocument_USCORErevision, "ns1:get_document_revision", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_16)
		return soap_closesock(soap);
	soap_default_ns1__get_USCOREdocument_USCORErevisionResponse(soap, _param_16);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__get_USCOREdocument_USCORErevisionResponse(soap, _param_16, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__search_USCOREby_USCOREmodule(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *search_USCOREstring, struct select_USCOREfields *modules, int offset, int max_USCOREresults, char *assigned_USCOREuser_USCOREid, struct select_USCOREfields *select_USCOREfields, enum xsd__boolean unified_USCOREsearch_USCOREonly, enum xsd__boolean favorites, struct ns1__search_USCOREby_USCOREmoduleResponse *_param_17)
{	struct ns1__search_USCOREby_USCOREmodule soap_tmp_ns1__search_USCOREby_USCOREmodule;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.124.27/crm/service/v4_1/soap.php";
	if (!soap_action)
		soap_action = "http://192.168.124.27/crm/service/v4_1/soap.php/search_by_module";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__search_USCOREby_USCOREmodule.session = session;
	soap_tmp_ns1__search_USCOREby_USCOREmodule.search_USCOREstring = search_USCOREstring;
	soap_tmp_ns1__search_USCOREby_USCOREmodule.modules = modules;
	soap_tmp_ns1__search_USCOREby_USCOREmodule.offset = offset;
	soap_tmp_ns1__search_USCOREby_USCOREmodule.max_USCOREresults = max_USCOREresults;
	soap_tmp_ns1__search_USCOREby_USCOREmodule.assigned_USCOREuser_USCOREid = assigned_USCOREuser_USCOREid;
	soap_tmp_ns1__search_USCOREby_USCOREmodule.select_USCOREfields = select_USCOREfields;
	soap_tmp_ns1__search_USCOREby_USCOREmodule.unified_USCOREsearch_USCOREonly = unified_USCOREsearch_USCOREonly;
	soap_tmp_ns1__search_USCOREby_USCOREmodule.favorites = favorites;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__search_USCOREby_USCOREmodule(soap, &soap_tmp_ns1__search_USCOREby_USCOREmodule);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__search_USCOREby_USCOREmodule(soap, &soap_tmp_ns1__search_USCOREby_USCOREmodule, "ns1:search_by_module", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__search_USCOREby_USCOREmodule(soap, &soap_tmp_ns1__search_USCOREby_USCOREmodule, "ns1:search_by_module", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_17)
		return soap_closesock(soap);
	soap_default_ns1__search_USCOREby_USCOREmoduleResponse(soap, _param_17);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__search_USCOREby_USCOREmoduleResponse(soap, _param_17, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREavailable_USCOREmodules(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *filter, struct ns1__get_USCOREavailable_USCOREmodulesResponse *_param_18)
{	struct ns1__get_USCOREavailable_USCOREmodules soap_tmp_ns1__get_USCOREavailable_USCOREmodules;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.124.27/crm/service/v4_1/soap.php";
	if (!soap_action)
		soap_action = "http://192.168.124.27/crm/service/v4_1/soap.php/get_available_modules";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__get_USCOREavailable_USCOREmodules.session = session;
	soap_tmp_ns1__get_USCOREavailable_USCOREmodules.filter = filter;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__get_USCOREavailable_USCOREmodules(soap, &soap_tmp_ns1__get_USCOREavailable_USCOREmodules);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__get_USCOREavailable_USCOREmodules(soap, &soap_tmp_ns1__get_USCOREavailable_USCOREmodules, "ns1:get_available_modules", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__get_USCOREavailable_USCOREmodules(soap, &soap_tmp_ns1__get_USCOREavailable_USCOREmodules, "ns1:get_available_modules", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_18)
		return soap_closesock(soap);
	soap_default_ns1__get_USCOREavailable_USCOREmodulesResponse(soap, _param_18);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__get_USCOREavailable_USCOREmodulesResponse(soap, _param_18, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREuser_USCOREteam_USCOREid(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char **return_)
{	struct ns1__get_USCOREuser_USCOREteam_USCOREid soap_tmp_ns1__get_USCOREuser_USCOREteam_USCOREid;
	struct ns1__get_USCOREuser_USCOREteam_USCOREidResponse *soap_tmp_ns1__get_USCOREuser_USCOREteam_USCOREidResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.124.27/crm/service/v4_1/soap.php";
	if (!soap_action)
		soap_action = "http://192.168.124.27/crm/service/v4_1/soap.php/get_user_team_id";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__get_USCOREuser_USCOREteam_USCOREid.session = session;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__get_USCOREuser_USCOREteam_USCOREid(soap, &soap_tmp_ns1__get_USCOREuser_USCOREteam_USCOREid);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__get_USCOREuser_USCOREteam_USCOREid(soap, &soap_tmp_ns1__get_USCOREuser_USCOREteam_USCOREid, "ns1:get_user_team_id", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__get_USCOREuser_USCOREteam_USCOREid(soap, &soap_tmp_ns1__get_USCOREuser_USCOREteam_USCOREid, "ns1:get_user_team_id", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!return_)
		return soap_closesock(soap);
	*return_ = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__get_USCOREuser_USCOREteam_USCOREidResponse = soap_get_ns1__get_USCOREuser_USCOREteam_USCOREidResponse(soap, NULL, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (return_ && soap_tmp_ns1__get_USCOREuser_USCOREteam_USCOREidResponse->return_)
		*return_ = *soap_tmp_ns1__get_USCOREuser_USCOREteam_USCOREidResponse->return_;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__set_USCOREcampaign_USCOREmerge(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, struct select_USCOREfields *targets, char *campaign_USCOREid, struct ns1__set_USCOREcampaign_USCOREmergeResponse *_param_19)
{	struct ns1__set_USCOREcampaign_USCOREmerge soap_tmp_ns1__set_USCOREcampaign_USCOREmerge;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.124.27/crm/service/v4_1/soap.php";
	if (!soap_action)
		soap_action = "http://192.168.124.27/crm/service/v4_1/soap.php/set_campaign_merge";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__set_USCOREcampaign_USCOREmerge.session = session;
	soap_tmp_ns1__set_USCOREcampaign_USCOREmerge.targets = targets;
	soap_tmp_ns1__set_USCOREcampaign_USCOREmerge.campaign_USCOREid = campaign_USCOREid;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__set_USCOREcampaign_USCOREmerge(soap, &soap_tmp_ns1__set_USCOREcampaign_USCOREmerge);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__set_USCOREcampaign_USCOREmerge(soap, &soap_tmp_ns1__set_USCOREcampaign_USCOREmerge, "ns1:set_campaign_merge", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__set_USCOREcampaign_USCOREmerge(soap, &soap_tmp_ns1__set_USCOREcampaign_USCOREmerge, "ns1:set_campaign_merge", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_19)
		return soap_closesock(soap);
	soap_default_ns1__set_USCOREcampaign_USCOREmergeResponse(soap, _param_19);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__set_USCOREcampaign_USCOREmergeResponse(soap, _param_19, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREentries_USCOREcount(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *module_USCOREname, char *query, int deleted, struct ns1__get_USCOREentries_USCOREcountResponse *_param_20)
{	struct ns1__get_USCOREentries_USCOREcount soap_tmp_ns1__get_USCOREentries_USCOREcount;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.124.27/crm/service/v4_1/soap.php";
	if (!soap_action)
		soap_action = "http://192.168.124.27/crm/service/v4_1/soap.php/get_entries_count";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__get_USCOREentries_USCOREcount.session = session;
	soap_tmp_ns1__get_USCOREentries_USCOREcount.module_USCOREname = module_USCOREname;
	soap_tmp_ns1__get_USCOREentries_USCOREcount.query = query;
	soap_tmp_ns1__get_USCOREentries_USCOREcount.deleted = deleted;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__get_USCOREentries_USCOREcount(soap, &soap_tmp_ns1__get_USCOREentries_USCOREcount);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__get_USCOREentries_USCOREcount(soap, &soap_tmp_ns1__get_USCOREentries_USCOREcount, "ns1:get_entries_count", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__get_USCOREentries_USCOREcount(soap, &soap_tmp_ns1__get_USCOREentries_USCOREcount, "ns1:get_entries_count", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_20)
		return soap_closesock(soap);
	soap_default_ns1__get_USCOREentries_USCOREcountResponse(soap, _param_20);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__get_USCOREentries_USCOREcountResponse(soap, _param_20, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREmodule_USCOREfields_USCOREmd5(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, struct select_USCOREfields *module_USCOREnames, struct ns1__get_USCOREmodule_USCOREfields_USCOREmd5Response *_param_21)
{	struct ns1__get_USCOREmodule_USCOREfields_USCOREmd5 soap_tmp_ns1__get_USCOREmodule_USCOREfields_USCOREmd5;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.124.27/crm/service/v4_1/soap.php";
	if (!soap_action)
		soap_action = "http://192.168.124.27/crm/service/v4_1/soap.php/get_module_fields_md5";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__get_USCOREmodule_USCOREfields_USCOREmd5.session = session;
	soap_tmp_ns1__get_USCOREmodule_USCOREfields_USCOREmd5.module_USCOREnames = module_USCOREnames;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__get_USCOREmodule_USCOREfields_USCOREmd5(soap, &soap_tmp_ns1__get_USCOREmodule_USCOREfields_USCOREmd5);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__get_USCOREmodule_USCOREfields_USCOREmd5(soap, &soap_tmp_ns1__get_USCOREmodule_USCOREfields_USCOREmd5, "ns1:get_module_fields_md5", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__get_USCOREmodule_USCOREfields_USCOREmd5(soap, &soap_tmp_ns1__get_USCOREmodule_USCOREfields_USCOREmd5, "ns1:get_module_fields_md5", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_21)
		return soap_closesock(soap);
	soap_default_ns1__get_USCOREmodule_USCOREfields_USCOREmd5Response(soap, _param_21);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__get_USCOREmodule_USCOREfields_USCOREmd5Response(soap, _param_21, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCORElast_USCOREviewed(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, struct module_USCOREnames *module_USCOREnames, struct ns1__get_USCORElast_USCOREviewedResponse *_param_22)
{	struct ns1__get_USCORElast_USCOREviewed soap_tmp_ns1__get_USCORElast_USCOREviewed;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.124.27/crm/service/v4_1/soap.php";
	if (!soap_action)
		soap_action = "http://192.168.124.27/crm/service/v4_1/soap.php/get_last_viewed";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__get_USCORElast_USCOREviewed.session = session;
	soap_tmp_ns1__get_USCORElast_USCOREviewed.module_USCOREnames = module_USCOREnames;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__get_USCORElast_USCOREviewed(soap, &soap_tmp_ns1__get_USCORElast_USCOREviewed);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__get_USCORElast_USCOREviewed(soap, &soap_tmp_ns1__get_USCORElast_USCOREviewed, "ns1:get_last_viewed", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__get_USCORElast_USCOREviewed(soap, &soap_tmp_ns1__get_USCORElast_USCOREviewed, "ns1:get_last_viewed", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_22)
		return soap_closesock(soap);
	soap_default_ns1__get_USCORElast_USCOREviewedResponse(soap, _param_22);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__get_USCORElast_USCOREviewedResponse(soap, _param_22, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREupcoming_USCOREactivities(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, struct ns1__get_USCOREupcoming_USCOREactivitiesResponse *_param_23)
{	struct ns1__get_USCOREupcoming_USCOREactivities soap_tmp_ns1__get_USCOREupcoming_USCOREactivities;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.124.27/crm/service/v4_1/soap.php";
	if (!soap_action)
		soap_action = "http://192.168.124.27/crm/service/v4_1/soap.php/get_upcoming_activities";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__get_USCOREupcoming_USCOREactivities.session = session;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__get_USCOREupcoming_USCOREactivities(soap, &soap_tmp_ns1__get_USCOREupcoming_USCOREactivities);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__get_USCOREupcoming_USCOREactivities(soap, &soap_tmp_ns1__get_USCOREupcoming_USCOREactivities, "ns1:get_upcoming_activities", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__get_USCOREupcoming_USCOREactivities(soap, &soap_tmp_ns1__get_USCOREupcoming_USCOREactivities, "ns1:get_upcoming_activities", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_23)
		return soap_closesock(soap);
	soap_default_ns1__get_USCOREupcoming_USCOREactivitiesResponse(soap, _param_23);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__get_USCOREupcoming_USCOREactivitiesResponse(soap, _param_23, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREmodified_USCORErelationships(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *module_USCOREname, char *related_USCOREmodule, char *from_USCOREdate, char *to_USCOREdate, int offset, int max_USCOREresults, int deleted, char *module_USCOREuser_USCOREid, struct select_USCOREfields *select_USCOREfields, char *relationship_USCOREname, char *deletion_USCOREdate, struct ns1__get_USCOREmodified_USCORErelationshipsResponse *_param_24)
{	struct ns1__get_USCOREmodified_USCORErelationships soap_tmp_ns1__get_USCOREmodified_USCORErelationships;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.124.27/crm/service/v4_1/soap.php";
	if (!soap_action)
		soap_action = "http://192.168.124.27/crm/service/v4_1/soap.php/get_modified_relationships";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__get_USCOREmodified_USCORErelationships.session = session;
	soap_tmp_ns1__get_USCOREmodified_USCORErelationships.module_USCOREname = module_USCOREname;
	soap_tmp_ns1__get_USCOREmodified_USCORErelationships.related_USCOREmodule = related_USCOREmodule;
	soap_tmp_ns1__get_USCOREmodified_USCORErelationships.from_USCOREdate = from_USCOREdate;
	soap_tmp_ns1__get_USCOREmodified_USCORErelationships.to_USCOREdate = to_USCOREdate;
	soap_tmp_ns1__get_USCOREmodified_USCORErelationships.offset = offset;
	soap_tmp_ns1__get_USCOREmodified_USCORErelationships.max_USCOREresults = max_USCOREresults;
	soap_tmp_ns1__get_USCOREmodified_USCORErelationships.deleted = deleted;
	soap_tmp_ns1__get_USCOREmodified_USCORErelationships.module_USCOREuser_USCOREid = module_USCOREuser_USCOREid;
	soap_tmp_ns1__get_USCOREmodified_USCORErelationships.select_USCOREfields = select_USCOREfields;
	soap_tmp_ns1__get_USCOREmodified_USCORErelationships.relationship_USCOREname = relationship_USCOREname;
	soap_tmp_ns1__get_USCOREmodified_USCORErelationships.deletion_USCOREdate = deletion_USCOREdate;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__get_USCOREmodified_USCORErelationships(soap, &soap_tmp_ns1__get_USCOREmodified_USCORErelationships);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__get_USCOREmodified_USCORErelationships(soap, &soap_tmp_ns1__get_USCOREmodified_USCORErelationships, "ns1:get_modified_relationships", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__get_USCOREmodified_USCORErelationships(soap, &soap_tmp_ns1__get_USCOREmodified_USCORErelationships, "ns1:get_modified_relationships", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_24)
		return soap_closesock(soap);
	soap_default_ns1__get_USCOREmodified_USCORErelationshipsResponse(soap, _param_24);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__get_USCOREmodified_USCORErelationshipsResponse(soap, _param_24, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
